# This is a workflow that will automatically sync your Peloton rides with Garmin

name: 🔄 Sync Workflow

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      workoutsToDownload:
        type: number
        default: "5"
      saveLocalCopy:
        type: boolean
        default: false
  schedule:
    - cron: '0 1 * * *'

env:
  OUTPUT_DIR: /app/output

jobs:
  sync:
    name: 🔄 Sync
    runs-on: ubuntu-latest
    container: 
      image:  philosowaffle/peloton-to-garmin:console-stable
      options: --user root
    steps:

    - name: 📁Create output directory
      run: mkdir -p ${{ env.OUTPUT_DIR }}

    - name: 🗃 Create config file
      env:
        DEFAULT_WORKOUT_NUM: 10
      run: |
        cat <<EOT > /app/configuration.local.json 
        {
          "App": {
            "EnablePolling": false,
            "CheckForUpdates": true,
            "CloseConsoleOnFinish": true
          },
          "Format": {
            "Fit": true,
            "Json": false,
            "Tcx": false,
            "SaveLocalCopy": ${{ github.event.inputs.saveLocalCopy || false }},
            "IncludeTimeInHRZones": false,
            "IncludeTimeInPowerZones": false,
            "StackedWorkouts": {
              "AutomaticallyStackWorkouts": false,
              "MaxAllowedGapSeconds": 300
            }
          },
          "Peloton": {
            "NumWorkoutsToDownload": ${{ github.event.inputs.workoutsToDownload || env.DEFAULT_WORKOUT_NUM }},
          },
          "Garmin": {
            "Upload": true,
            "FormatToUpload": "fit"
          },
          "Observability": {
            "Prometheus": {
              "Enabled": false
            },
            "Jaeger": {
              "Enabled": false
            },
            "Serilog": {
              "Using": [ "Serilog.Sinks.Console"],
              "MinimumLevel": "Information"
            }
          },
          "DeviceInfoSettings": {
            "none": {
               "name": "Instinct 2S",
              "unitId": 3467573777,
              "productID": 3889,
              "version": {
                "versionMajor": 16,
                "versionMinor": 11,
                "buildMajor": 0,
                "buildMinor": 0
              }
            },
            "cycling": {
              "name": "Instinct 2S",
              "unitId": 3467573777,
              "productID": 3889,
              "version": {
                "versionMajor": 16,
                "versionMinor": 11,
                "buildMajor": 0,
                "buildMinor": 0
              }
            },
            "rowing": {
              "name": "Epix",
              "unitId": 3413684246,
              "productID": 3943,
              "manufacturerId": 1,
              "version": {
                "versionMajor": 10,
                "versionMinor": 43.0,
                "buildMajor": 0,
                "buildMinor": 0.0
              }
            }
          },
          "Cycling": {
            "PreferredLapType": "Class_Targets"
          },
          "Running": {
            "PreferredLapType": "Distance"
          },
          "Rowing": {
            "PreferredLapType": "Class_Segments"
          },
          "Strength": {
            "DefaultSecondsPerRep": 3
          },
          "WorkoutTitleTemplate": "{Peloton - {PelotonWorkoutTitle}} with {{PelotonInstructorName}}"
        }
        },
        }
        EOT
    
    - name: ▶ Run P2G Sync
      run: /app/ConsoleClient
      if: ${{ env.P2G_PELOTON__EMAIL && env.P2G_PELOTON__PASSWORD && env.P2G_GARMIN__EMAIL && env.P2G_GARMIN__PASSWORD }}
      working-directory: /app
      env:
        P2G_PELOTON__EMAIL: ${{ secrets.P2G_PELOTON__EMAIL }}
        P2G_PELOTON__PASSWORD: ${{ secrets.P2G_PELOTON__PASSWORD }}
        P2G_GARMIN__EMAIL: ${{ secrets.P2G_GARMIN__EMAIL }}
        P2G_GARMIN__PASSWORD: ${{ secrets.P2G_GARMIN__PASSWORD }}
        TZ: America/New_York

    - name: ⤴ Upload output directory
      uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.saveLocalCopy == 'true' }}
      with:
        name: output
        path: ${{ env.OUTPUT_DIR }}
        if-no-files-found: error
